improbable_astro/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static #won't be needed when deployed via PaaS
from django.urls import include, path, re_path
# from django.conf.urls import url => url soon to be deprecated
from . import views 
import movies



urlpatterns = [

    path('movies/', include('movies.urls', namespace='movies')),# in treehous not working in v2?
    path('admin/', admin.site.urls),
    path('home/', views.hello_world, name='home'),
    path('', views.hello_world),
    re_path(r'^$', views.hello_world),
    #url(r'', views.hello_world).
    #path('movies_seen_by_user', movies.views.movies_seen_by_user),
    
    
    #url(r'(?P<user_pk>\d+)/$', movies.views.movies_seen_by_user),
    ]
""" below for treehouse demo version 1.8 """
    #url(r'^$', views.hello_world),

urlpatterns += staticfiles_urlpatterns() # only used for local development to locate static
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

movies/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views 


app_name = 'movies'

urlpatterns = [
    #path('all_movies/', views.all_movies, name='all_movies'),
    path('login/', views.login, name='login'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('movie_search/', views.movie_search, name='movie_search'),
    path('omdb_movie_data/', views.movie_search, name='omdb_data'),

    path('movies_list/', views.all_movies, name='all_movies'),

    re_path(r'movies_seen_by_user/(?P<user_pk>\d+)/$', views.movies_seen_by_user, name="movies_by_user"),
    re_path(r'(?P<pk>\d+)/$', views.movie_detail, name='movie_detes'),
    re_path(r'^new_movie_review/$', views.movie_review, name='movie_review'),


    #url(r'(?P<pk>\d+)/$', views.movie_detail),
    #url(r'movies_seen_by_user/(?P<user_pk>\d+)/$', views.movies_seen_by_user),
    
    #url(r'(?P<user_pk>\d+)/$', views.movies_seen_by_user)
    # path('movies_seen_by_user', views.movies_seen_by_user),
    #path('home', improbable_astro.views.hello_world),
]

templates/base.html
{% load static from staticfiles %}


<!DOCTYPE>
<html>
<head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    {% block static %}
  
    {% endblock %}
</head>
<body>
    
    <div class="site-container">
            <nav>
                    <!-- using name of path                -->
                    <a href="{% url 'home' %}">Home</a>
                    <a href="{% url 'movies:movie_search' %}">Movie Search</a>
                    <a href="{% url 'movies:all_movies' %}">All Movies Reviewed</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'movies:movie_review' %}">Review a Movie</a>
                    {% endif %}

                    <!-- below causes pile ups at url name
                    <a href="all_movies">All Movies Reviewed</a> -->
                </nav>
    {% block content %}
    
    {% endblock %}
    </div>
</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Hi, this home, you live here now!</h1>


<a href="{% url 'movies:login' %}">Login</a>
</br>
</br>
<a href="{% url 'movies:sign_up' %}">Sign Me UP!</a>

{% endblock %}